#import "./planets.gql"
#import "./persons.gql"
#import "./utils.gql"
#import "./species.gql"
#import "./vehicles.gql"
#import "./starships.gql"

"""
L'entrée principale du schéma
"""
type Query {
    "Les personnages de starwars en pagination"
    allPersons(pageSize: Int, after: String, before: String):AllPersonsResponse!
    "Une personne de starwars"
    person(id: ID!):Person
    "Les planètes de starwars en pagination"
    allPlanets(pageSize: Int, after: String, before: String):AllPlanetsResponse!
    "Une planète de starwars"
    planet(id: ID!):Planet
    "Les espèces de starwars en pagination"
    allSpecies(pageSize: Int, after: String, before: String):AllSpeciesResponse!
    "Une espèce de starwars"
    specie(id: ID!):Specie
    "Les véhicules de starwars en pagination"
    allVehicles(pageSize: Int, after: String, before: String):AllVehiclesResponse!
    "Un véhicule de starwars"
    vehicle(id: ID!):Vehicle
    "Les vaiseaux de starwars en pagination"
    allStarships(pageSize: Int, after: String, before: String):AllStarshipsResponse!
    "Un vaisseau de starwars"
    starship(id: ID!):Starship
}