"""
La pagination pour les personnages de starwars
"""
type AllPersonsResponse{
    "Information de la pagination"
    pageInfo: PageInfo
    "Une page de personnes"
    persons:[Person]
}

"""
Le type personne
"""
type Person{
    "L'identifiant unique de la personne"
    id: ID!
    "Le nom de la personne"
    name: String!
    "La date de naissance de la personne en BBY"
    birthYear: String
    "Les couleurs des yeux de la personne"
    eyeColor: String
    "Le sexe de la personne"
    gender: String
    "La couleur des cheveux de la personne"
    hairColor: String
    "La taille de la personne"
    height: Int
    "Le poids de la personne"
    mass: Float
    "La couleur de peau de la personne"
    skinColor: String
    "La planète de la personne"
    homeworld: Planet
    "L'espèce de la personne"
    specie: Specie
    "Les vaisseaux de la personne"
    starships(pageSize: Int, after: String, before: String):AllStarshipsResponse!
    "Les véhicules de la personne"
    vehicles(pageSize: Int, after: String, before: String):AllVehiclesResponse!
    "Les informations supplémentaires de la personne"
    more: ObjectMore
}